# Generated by Django 5.2.11 on 2026-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido(s)')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula / Documento')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('banco', models.CharField(blank=True, choices=[('Nequi', 'Nequi'), ('Bancolombia', 'Bancolombia'), ('Banco de Bogotá', 'Banco de Bogotá'), ('Davivienda', 'Davivienda'), ('Daviplata', 'Daviplata'), ('Nu', 'Nu'), ('BBVA', 'BBVA')], max_length=100, null=True, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], max_length=20, null=True, verbose_name='Tipo de Cuenta')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta Bancaria')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
                'db_table': 'prog_monitores',
            },
        ),
    ]
