# Generated by Django 5.2.11 on 2026-06-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColegioSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Colegio de simulacro',
                'verbose_name_plural': 'Colegios de simulacro',
                'db_table': 'prog_simulacro_colegios',
                'ordering': ['nombre'],
            },
        ),
    ]
