# Generated by Django 5.2.11 on 2026-06-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0019_backfill_cancelaciones'),
        ('monitores', '0002_colegiosimulacro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='monitores.monitor', verbose_name='Monitor')),
            ],
            options={
                'verbose_name': 'Asignación de monitor',
                'verbose_name_plural': 'Asignaciones de monitor',
                'db_table': 'prog_simulacros_monitores',
            },
        ),
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio_nombre', models.CharField(blank=True, max_length=200, verbose_name='Colegio (snapshot)')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('TODO_DIA', 'Todo el día')], default='TODO_DIA', max_length=10, verbose_name='Jornada')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='Valor por monitor (COP)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacros', to='monitores.colegiosimulacro', verbose_name='Colegio')),
                ('grados', models.ManyToManyField(blank=True, related_name='simulacros', to='colegios.grado', verbose_name='Grados')),
                ('monitores', models.ManyToManyField(blank=True, related_name='simulacros', through='monitores.AsignacionMonitor', to='monitores.monitor', verbose_name='Monitores')),
            ],
            options={
                'verbose_name': 'Simulacro',
                'verbose_name_plural': 'Simulacros',
                'db_table': 'prog_simulacros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='asignacionmonitor',
            name='simulacro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='monitores.simulacro', verbose_name='Simulacro'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionmonitor',
            unique_together={('simulacro', 'monitor')},
        ),
    ]
