# Generated by Django 5.2.11 on 2026-06-23 18:17

import django.db.models.deletion
import programacion.monitores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0003_asignacionmonitor_simulacro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMonitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de la semana')),
                ('fecha_fin', models.DateField(verbose_name='Fin de la semana')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado')], default='BORRADOR', max_length=10)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_monitores_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Lote de pagos de monitores',
                'verbose_name_plural': 'Lotes de pagos de monitores',
                'db_table': 'prog_monitores_pagos_lotes',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PagoMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del simulacro')),
                ('valor', models.IntegerField(verbose_name='Valor del simulacro (COP)')),
                ('excluida', models.BooleanField(default=False, verbose_name='Excluida del envío')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas', to='monitores.lotemonitores', verbose_name='Lote')),
                ('marcado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_monitores_marcados', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='monitores.monitor', verbose_name='Monitor')),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='monitores.simulacro', verbose_name='Simulacro')),
            ],
            options={
                'verbose_name': 'Pago de monitor',
                'verbose_name_plural': 'Pagos de monitores',
                'db_table': 'prog_monitores_pagos',
                'ordering': ['-fecha', 'monitor__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExtraPagoMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('valor', models.PositiveIntegerField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='monitores.pagomonitor')),
            ],
            options={
                'verbose_name': 'Costo extra de pago de monitor',
                'verbose_name_plural': 'Costos extra de pago de monitor',
                'db_table': 'prog_monitores_pagos_extras',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoportePagoMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=programacion.monitores.models._monitor_soporte_upload_to)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='monitores.pagomonitor')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_pago_monitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soporte de pago a monitor',
                'verbose_name_plural': 'Soportes de pago a monitor',
                'db_table': 'prog_monitores_pagos_soportes',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='lotemonitores',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'BORRADOR')), fields=('fecha_inicio', 'fecha_fin'), name='unique_lote_monitores_borrador_por_semana'),
        ),
        migrations.AlterUniqueTogether(
            name='pagomonitor',
            unique_together={('monitor', 'simulacro')},
        ),
    ]
