# Generated by Django 5.2.11 on 2026-06-02 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0023_alter_colegio_table_alter_colegioanio_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_nombre', models.CharField(max_length=200)),
                ('docente_cedula', models.CharField(blank=True, max_length=50)),
                ('docente_cuenta', models.CharField(blank=True, max_length=50)),
                ('colegio_codigo', models.CharField(blank=True, max_length=50)),
                ('colegio_nombre', models.CharField(max_length=200)),
                ('fecha_viaje', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('DEVUELTA', 'Devuelta'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], default='ENVIADA', max_length=10)),
                ('motivo_devolucion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('devuelto_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaticos', to='configuracion.colegio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaticos_creados', to=settings.AUTH_USER_MODEL)),
                ('gestionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaticos', to='configuracion.profesor')),
            ],
            options={
                'verbose_name': 'Solicitud de viáticos',
                'verbose_name_plural': 'Solicitudes de viáticos',
                'db_table': 'prog_viaticos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GastoViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.PositiveIntegerField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viaticos.solicitudviatico')),
            ],
            options={
                'db_table': 'prog_viaticos_gastos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
