# Generated by Django 5.2.11 on 2026-06-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudviatico',
            name='docente_banco',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
