# Generated by Django 5.2.11 on 2026-06-03 15:44

import django.db.models.deletion
import programacion.viaticos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0002_solicitudviatico_docente_banco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoportePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=programacion.viaticos.models._soporte_upload_to)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='viaticos.solicitudviatico')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_viatico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soporte de pago',
                'verbose_name_plural': 'Soportes de pago',
                'db_table': 'prog_viaticos_soportes',
                'ordering': ['-subido_en'],
            },
        ),
    ]
