# Generated by Django 5.2.11 on 2026-06-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0003_soportepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudviatico',
            name='finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudviatico',
            name='legalizacion_devuelta_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudviatico',
            name='legalizacion_enviada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soportepago',
            name='tipo',
            field=models.CharField(choices=[('PAGO', 'Soporte de pago'), ('LEGALIZACION', 'Soporte de legalización')], default='PAGO', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitudviatico',
            name='estado',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('DEVUELTA', 'Devuelta'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada'), ('LEG_ENVIADA', 'Legalización enviada'), ('LEG_DEVUELTA', 'Legalización devuelta'), ('FINALIZADA', 'Finalizada')], default='ENVIADA', max_length=20),
        ),
    ]
