# Generated by Django 5.2.11 on 2026-06-11 14:53

import django.db.models.deletion
import logistica.inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'log_bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'log_categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='log_inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_entradas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=logistica.inventario.models._adjunto_entrada_upload_to)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_inventario', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='log_inventario.entrada')),
            ],
            options={
                'db_table': 'log_entradas_adjuntos',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('PAQUETE', 'Paquete'), ('CAJA', 'Caja'), ('RESMA', 'Resma')], default='UNIDAD', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='log_inventario.categoria')),
            ],
            options={
                'verbose_name': 'Artículo',
                'db_table': 'log_articulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('OTORGADO', 'Prestamos nosotros'), ('RECIBIDO', 'Nos prestan')], default='OTORGADO', max_length=10)),
                ('tercero_nombre', models.CharField(max_length=200)),
                ('tercero_documento', models.CharField(blank=True, max_length=50)),
                ('fecha_compromiso', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PARCIAL', 'Devuelto parcial'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'db_table': 'log_prestamos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_inventario', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='log_inventario.prestamo')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'log_prestamos_devoluciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'log_terceros',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('documento',), name='unique_tercero_documento')],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tercero_nombre', models.CharField(blank=True, max_length=200)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='log_inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_inventario', to=settings.AUTH_USER_MODEL)),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='log_inventario.tercero')),
            ],
            options={
                'db_table': 'log_salidas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='log_inventario.tercero'),
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrantes', to='log_inventario.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salientes', to='log_inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_traslados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('PRESTAMO', 'Préstamo otorgado'), ('DEVOLUCION', 'Devolución de préstamo otorgado'), ('PREST_RECIBIDO', 'Préstamo recibido'), ('DEV_RECIBIDO', 'Devolución de préstamo recibido'), ('TRASLADO_SAL', 'Traslado (salida)'), ('TRASLADO_ENT', 'Traslado (entrada)'), ('AJUSTE_POS', 'Ajuste positivo'), ('AJUSTE_NEG', 'Ajuste negativo')], max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('saldo_resultante', models.PositiveIntegerField()),
                ('detalle', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.devolucion')),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.entrada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.item')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.prestamo')),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.salida')),
                ('traslado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.traslado')),
            ],
            options={
                'db_table': 'log_movimientos',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrasladoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='log_inventario.item')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='log_inventario.traslado')),
            ],
            options={
                'db_table': 'log_traslados_lineas',
            },
        ),
        migrations.CreateModel(
            name='EntradaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='log_inventario.entrada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='log_inventario.item')),
            ],
            options={
                'db_table': 'log_entradas_lineas',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='entrada_linea_cantidad_positiva')],
            },
        ),
        migrations.CreateModel(
            name='PrestamoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prestada', models.PositiveIntegerField()),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='log_inventario.bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='log_inventario.item')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='log_inventario.prestamo')),
            ],
            options={
                'db_table': 'log_prestamos_lineas',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_prestada__gt', 0)), name='prestamo_linea_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('cantidad_devuelta__lte', models.F('cantidad_prestada'))), name='prestamo_linea_devuelta_lte_prestada')],
            },
        ),
        migrations.CreateModel(
            name='SalidaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='log_inventario.item')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='log_inventario.salida')),
            ],
            options={
                'db_table': 'log_salidas_lineas',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='salida_linea_cantidad_positiva')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='log_inventario.bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='log_inventario.item')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'db_table': 'log_stock',
                'constraints': [models.UniqueConstraint(fields=('item', 'bodega'), name='unique_stock_item_bodega')],
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado', 'fecha_compromiso'], name='log_prestam_estado_fabdf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='traslado',
            constraint=models.CheckConstraint(condition=models.Q(('bodega_origen', models.F('bodega_destino')), _negated=True), name='traslado_bodegas_distintas'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['item', 'bodega', 'creado_en'], name='log_movimie_item_id_1e4dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['item', 'creado_en'], name='log_movimie_item_id_45c078_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo', 'creado_en'], name='log_movimie_tipo_b2593f_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movimiento_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='trasladolinea',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='traslado_linea_cantidad_positiva'),
        ),
    ]
