# Generated by Django 5.2.11 on 2026-07-27 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_inventario', '0002_item_material_grados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('PRESTAMO', 'Préstamo otorgado'), ('DEVOLUCION', 'Devolución de préstamo otorgado'), ('PREST_RECIBIDO', 'Préstamo recibido'), ('DEV_RECIBIDO', 'Devolución de préstamo recibido'), ('TRASLADO_SAL', 'Traslado (salida)'), ('TRASLADO_ENT', 'Traslado (entrada)'), ('AJUSTE_POS', 'Ajuste positivo'), ('AJUSTE_NEG', 'Ajuste negativo'), ('DEV_COLEGIO', 'Devolución de colegio')], max_length=15),
        ),
        migrations.CreateModel(
            name='DevolucionColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField()),
                ('colegio', models.CharField(max_length=200)),
                ('codigo_colegio', models.CharField(blank=True, max_length=60)),
                ('regional', models.CharField(blank=True, max_length=120)),
                ('ejecutivo', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_colegio', to='log_inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_colegio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución de colegio',
                'verbose_name_plural': 'Devoluciones de colegios',
                'db_table': 'log_devoluciones_colegios',
                'ordering': ['-fecha_recibido', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='devolucion_colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='log_inventario.devolucioncolegio'),
        ),
        migrations.CreateModel(
            name='DevolucionColegioLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='log_inventario.devolucioncolegio')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='log_inventario.item')),
            ],
            options={
                'db_table': 'log_devoluciones_colegios_lineas',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='devolucion_colegio_linea_positiva')],
            },
        ),
    ]
