# Generated by Django 5.2.11 on 2026-07-27 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_inventario', '0003_devoluciones_colegios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucioncolegio',
            name='motivo_no_valida',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='devolucioncolegio',
            name='valida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='devolucioncolegio',
            constraint=models.CheckConstraint(condition=models.Q(('valida', True), models.Q(('motivo_no_valida', ''), _negated=True), _connector='OR'), name='devolucion_colegio_no_valida_con_motivo'),
        ),
    ]
