# Generated by Django 5.2.11 on 2026-07-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_inventario', '0004_devolucion_colegio_valida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_inv_asignadas', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='log_inventario.bodega')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodega_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodega por usuario (inventario)',
                'verbose_name_plural': 'Bodegas por usuario (inventario)',
                'db_table': 'log_bodegas_usuarios',
                'ordering': ['usuario__username'],
            },
        ),
    ]
