# Generated by Django 5.2.11 on 2026-06-10 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_lotes_extras_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lotepagos',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lotepagos',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'BORRADOR')), fields=('fecha_inicio', 'fecha_fin'), name='unique_lote_borrador_por_semana'),
        ),
    ]
