# Generated by Django 5.2.11 on 2026-03-06 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0003_alter_profesor_banco_alter_profesor_disponibilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_texto', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='configuracion.colegio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_colegio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Colegio',
                'verbose_name_plural': 'Usuarios de Colegios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_texto', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='configuracion.profesor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Profesor',
                'verbose_name_plural': 'Usuarios de Profesores',
            },
        ),
    ]
