# Generated by Django 5.2.11 on 2026-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocolegio',
            name='password_texto',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarioprofesor',
            name='password_texto',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
    ]
