# Generated by Django 5.2.11 on 2026-04-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariocolegio_password_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocolegio',
            name='password_texto',
        ),
        migrations.RemoveField(
            model_name='usuarioprofesor',
            name='password_texto',
        ),
    ]
