# Generated by Django 5.2.11 on 2026-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_grupo_area_programacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuariocolegio',
            table='usuarios_colegio',
        ),
        migrations.AlterModelTable(
            name='usuarioprofesor',
            table='usuarios_profesor',
        ),
    ]
