# Generated by Django 5.2.11 on 2026-06-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilempleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('stack', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('breadcrumbs', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error de cliente',
                'verbose_name_plural': 'Errores de cliente',
                'db_table': 'usuarios_errores_cliente',
                'ordering': ['-creado_en'],
            },
        ),
    ]
