# Generated by Django 5.2.11 on 2026-07-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_grupo_area_logistica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('modulo', models.CharField(max_length=40)),
                ('nivel', models.CharField(choices=[('SIN', 'Sin acceso'), ('LEC', 'Solo lectura'), ('COM', 'Completo')], max_length=3)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_override', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override de módulo',
                'verbose_name_plural': 'Overrides de módulo',
                'db_table': 'usuarios_modulos',
                'constraints': [models.UniqueConstraint(fields=('user', 'area', 'modulo'), name='unique_modulo_por_usuario')],
            },
        ),
    ]
