# Generated by Django 5.2.11 on 2026-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0002_tarea_completado_por'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarea',
            table='prog_tareas',
        ),
    ]
