# Generated by Django 5.2.11 on 2026-04-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0010_materia_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('duplicado', 'Unidad Duplicada'), ('conflicto', 'Choque de Profesor'), ('secuencia', 'Salto de Secuencia')], max_length=20)),
                ('huella', models.CharField(help_text='Hash único que identifica este error concreto para evitar duplicados.', max_length=255, unique=True)),
                ('mensaje', models.TextField()),
                ('vigente', models.BooleanField(db_index=True, default=True)),
                ('detectado', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='configuracion.colegio')),
                ('colegios_implicados', models.ManyToManyField(blank=True, help_text='Para conflictos de profesor que involucran varios colegios.', related_name='alertas_implicado', to='configuracion.colegio')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='configuracion.profesor')),
            ],
            options={
                'verbose_name': 'Alerta de Auditoría',
                'verbose_name_plural': 'Alertas de Auditoría',
                'ordering': ['-detectado'],
            },
        ),
    ]
