# Generated by Django 5.2.11 on 2026-04-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('configuracion', '0011_alter_profesor_eps_alter_profesor_fondo_pension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertaauditoria',
            index=models.Index(fields=['colegio', 'vigente'], name='auditoria_a_colegio_448e03_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaauditoria',
            index=models.Index(fields=['tipo'], name='auditoria_a_tipo_ac582a_idx'),
        ),
    ]
