# Generated by Django 5.2.11 on 2026-04-05 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alertaauditoria_auditoria_a_colegio_448e03_idx_and_more'),
        ('configuracion', '0015_alter_colegio_options_alter_colegio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaauditoria',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='configuracion.colegioaño'),
        ),
        migrations.AlterField(
            model_name='alertaauditoria',
            name='colegios_implicados',
            field=models.ManyToManyField(blank=True, help_text='Para conflictos de profesor que involucran varios colegios.', related_name='alertas_implicado', to='configuracion.colegioaño'),
        ),
    ]
