# Generated by Django 5.2.11 on 2026-04-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_alertaauditoria_colegio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaauditoria',
            name='ignorado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_ignoradas', to=settings.AUTH_USER_MODEL, verbose_name='Ignorado por'),
        ),
        migrations.AddField(
            model_name='alertaauditoria',
            name='motivo_ignorado',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para ignorar'),
        ),
    ]
