# Generated by Django 5.2.11 on 2026-04-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_alertaauditoria_ignorar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaauditoria',
            name='huella',
            field=models.CharField(help_text='Hash MD5 determinista que identifica este error concreto. Permite deduplicar sin buscar por múltiples campos.', max_length=255, unique=True),
        ),
    ]
