# Generated by Django 5.2.11 on 2026-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_alter_alertaauditoria_huella'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertaauditoria',
            new_name='prog_alerta_colegio_6f916f_idx',
            old_name='auditoria_a_colegio_448e03_idx',
        ),
        migrations.RenameIndex(
            model_name='alertaauditoria',
            new_name='prog_alerta_tipo_93d19a_idx',
            old_name='auditoria_a_tipo_ac582a_idx',
        ),
        migrations.AlterModelTable(
            name='alertaauditoria',
            table='prog_alertas_auditoria',
        ),
    ]
