# Generated by Django 5.2.11 on 2026-04-14 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0022_alter_materia_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la clase')),
                ('horas', models.FloatField(verbose_name='Horas dictadas')),
                ('valor', models.IntegerField(verbose_name='Valor pagado (COP)')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='configuracion.colegioanio', verbose_name='Colegio/Año')),
                ('marcado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_marcados', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='configuracion.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Pago Realizado',
                'verbose_name_plural': 'Pagos Realizados',
                'ordering': ['-fecha', 'profesor__nombre'],
                'unique_together': {('profesor', 'colegio', 'fecha')},
            },
        ),
    ]
