# Generated by Django 5.2.11 on 2026-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pagorealizado',
            table='prog_pagos',
        ),
    ]
