# Generated by Django 5.2.11 on 2026-06-04 03:12

import django.db.models.deletion
import programacion.pagos.models  # los modelos se movieron a la sub-app `pagos`
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportar', '0002_alter_pagorealizado_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoportePagoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=programacion.pagos.models._pago_soporte_upload_to)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='exportar.pagorealizado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soporte de pago a profesor',
                'verbose_name_plural': 'Soportes de pago a profesor',
                'db_table': 'prog_pagos_soportes',
                'ordering': ['-subido_en'],
            },
        ),
    ]
