# Generated by Django 5.2.11 on 2026-07-17 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Artículo ERP',
                'verbose_name_plural': 'Artículos ERP',
                'db_table': 'log_despachos_articulos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=120)),
                ('asignado_en', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodega_despachos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de bodega',
                'verbose_name_plural': 'Asignaciones de bodega',
                'db_table': 'log_despachos_bodegas_usuarios',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='CargaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('max_fecha_orden', models.DateTimeField(blank=True, null=True)),
                ('n_filas', models.PositiveIntegerField(default=0)),
                ('n_ordenes', models.PositiveIntegerField(default=0)),
                ('n_nuevas', models.PositiveIntegerField(default=0)),
                ('n_actualizadas', models.PositiveIntegerField(default=0)),
                ('n_cerradas_auto', models.PositiveIntegerField(default=0)),
                ('n_alertas_remision', models.PositiveIntegerField(default=0)),
                ('n_descartadas', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_despachos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de reporte',
                'verbose_name_plural': 'Cargas de reporte',
                'db_table': 'log_despachos_cargas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden', models.CharField(max_length=30, unique=True)),
                ('sucursal', models.CharField(blank=True, max_length=120)),
                ('centro_costos', models.CharField(blank=True, max_length=120)),
                ('bodega', models.CharField(blank=True, db_index=True, max_length=120)),
                ('estado_orden_erp', models.CharField(blank=True, max_length=120)),
                ('estado_facturacion', models.CharField(blank=True, max_length=200)),
                ('vigencia', models.CharField(blank=True, max_length=60)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('id_cliente', models.CharField(blank=True, max_length=60)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('departamento', models.CharField(blank=True, max_length=120)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('vendedor', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_orden', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ALISTADA', 'Alistada'), ('DESPACHADA', 'Despachada'), ('REMITIDA', 'Remitida (cerrada en ERP)'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=12)),
                ('alistada_en', models.DateTimeField(blank=True, null=True)),
                ('despachada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_sin_marcar', models.BooleanField(default=False)),
                ('alerta_remision', models.BooleanField(default=False)),
                ('es_despachable', models.BooleanField(default=True)),
                ('n_lineas', models.PositiveIntegerField(default=0)),
                ('resumen_articulos', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alistada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_alistadas', to=settings.AUTH_USER_MODEL)),
                ('despachada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_despachadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de despacho',
                'verbose_name_plural': 'Órdenes de despacho',
                'db_table': 'log_despachos_ordenes',
                'ordering': ['fecha_entrega', 'id_orden'],
            },
        ),
        migrations.CreateModel(
            name='LineaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_articulo', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('es_material', models.BooleanField(default=True)),
                ('orden_archivo', models.PositiveIntegerField(default=0)),
                ('cantidad_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambiado_en', models.DateTimeField(blank=True, null=True)),
                ('pendiente_erp', models.BooleanField(default=False)),
                ('eliminada_erp', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='log_despachos.articuloerp')),
                ('articulo_cambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_como_cambio', to='log_despachos.articuloerp')),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_cambiadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='log_despachos.ordendespacho')),
            ],
            options={
                'verbose_name': 'Línea de orden',
                'verbose_name_plural': 'Líneas de orden',
                'db_table': 'log_despachos_lineas',
                'ordering': ['orden_archivo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALISTADA', 'Alistada'), ('DESPACHADA', 'Despachada'), ('REVERTIDA', 'Revertida'), ('CIERRE_AUTO', 'Cierre automático (despachada)'), ('CIERRE_SIN_MARCAR', 'Cerrada en ERP sin marcar'), ('ALERTA_REMISION', 'Despachada sin remisión'), ('CAMBIO_MATERIAL', 'Cambio de material'), ('CAMBIO_REVERTIDO', 'Cambio de material revertido'), ('ERP_ACTUALIZADO', 'Cambio actualizado en ERP'), ('LINEA_HUERFANA', 'Línea con cambio eliminada en ERP')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='log_despachos.cargareporte')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_despachos', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='log_despachos.ordendespacho')),
            ],
            options={
                'verbose_name': 'Evento de orden',
                'verbose_name_plural': 'Eventos de orden',
                'db_table': 'log_despachos_eventos',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordendespacho',
            index=models.Index(fields=['estado', 'fecha_entrega'], name='log_despach_estado_3182d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lineaorden',
            index=models.Index(fields=['orden', 'cod_articulo'], name='log_despach_orden_i_8f816f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoorden',
            index=models.Index(fields=['orden', 'creado_en'], name='log_despach_orden_i_468189_idx'),
        ),
    ]
