# Generated by Django 5.2.11 on 2026-02-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('libro_titulo', models.CharField(max_length=200, verbose_name='Libro')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.colegio')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones de Libros',
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('materia', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('es_evento', models.BooleanField(default=False, verbose_name='¿Es un evento especial?')),
                ('titulo_evento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título del Evento')),
                ('cancelada', models.BooleanField(default=False, verbose_name='¿Clase Cancelada?')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios / Motivo')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.bloque')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.colegio')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.profesor')),
            ],
            options={
                'unique_together': {('fecha', 'bloque')},
            },
        ),
    ]
