# Generated by Django 5.2.11 on 2026-03-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=200, verbose_name='Nombre del Estudiante (Colegio)')),
                ('ciudad', models.CharField(default='Bucaramanga', max_length=100, verbose_name='Ciudad')),
                ('mapa_link', models.URLField(blank=True, null=True, verbose_name='Link de Maps')),
                ('fecha', models.DateField(verbose_name='Fecha de la Clase')),
                ('hora', models.CharField(max_length=50, verbose_name='Hora (Ej: 14:00 - 16:00)')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('material', models.CharField(max_length=200, verbose_name='Libro / Material')),
                ('materia', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name_plural': 'Clases Particulares',
            },
        ),
    ]
