# Generated by Django 5.2.11 on 2026-03-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_claseparticular'),
        ('configuracion', '0007_alter_colegio_options_colegio_activo_colegio_año_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Grado')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'Asignación de Libro', 'verbose_name_plural': 'Asignaciones de Libros'},
        ),
        migrations.AlterModelOptions(
            name='bloque',
            options={'ordering': ['grado__nombre', 'hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='claseparticular',
            options={'verbose_name': 'Clase Particular', 'verbose_name_plural': 'Clases Particulares'},
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='hora',
        ),
        migrations.AddField(
            model_name='bloque',
            name='hora_fin',
            field=models.TimeField(default='00:00', verbose_name='Hora de Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque',
            name='hora_inicio',
            field=models.TimeField(default='00:00', verbose_name='Hora de Inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='configuracion.colegio'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='configuracion.colegio'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colegios.grado', verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colegios.grado', verbose_name='Grado'),
        ),
    ]
