# Generated by Django 5.2.11 on 2026-03-28 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0003_grado_alter_asignacion_options_alter_bloque_options_and_more'),
        ('configuracion', '0008_profesor_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_tipo', models.CharField(max_length=50)),
                ('objeto_id', models.IntegerField()),
                ('objeto_str', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('crear', 'Creado'), ('editar', 'Editado'), ('eliminar', 'Eliminado')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, default='')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='configuracion.colegio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
