# Generated by Django 5.2.11 on 2026-04-05 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0005_normalizacion_bd'),
        ('configuracion', '0015_alter_colegio_options_alter_colegio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='configuracion.colegioaño'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='configuracion.colegioaño'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.colegioaño'),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='configuracion.colegioaño'),
        ),
    ]
