# Generated by Django 5.2.11 on 2026-04-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0006_alter_asignacion_colegio_alter_bloque_colegio_and_more'),
        ('configuracion', '0016_alter_colegioaño_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='configuracion.colegioanio'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='configuracion.colegioanio'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.colegioanio'),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='configuracion.colegioanio'),
        ),
    ]
