# Generated by Django 5.2.11 on 2026-04-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0007_alter_asignacion_colegio_alter_bloque_colegio_and_more'),
        ('configuracion', '0018_material_especial_libro_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='enlace_personalizado',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Personalizado'),
        ),
        migrations.AddField(
            model_name='clase',
            name='libro_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_especiales', to='configuracion.nombrelibro', verbose_name='Libro Especial'),
        ),
    ]
