# Generated by Django 5.2.11 on 2026-04-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0008_material_especial_libro_enlace'),
        ('configuracion', '0019_nombrelibro_es_material_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.nombrelibro', verbose_name='Libro'),
        ),
    ]
