# Generated by Django 5.2.11 on 2026-04-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0009_asignacion_libro_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='orden',
        ),
    ]
