# Generated by Django 5.2.11 on 2026-04-24 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0010_drop_bloque_orden'),
        ('configuracion', '0022_alter_materia_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['colegio', 'grado', 'fecha_inicio', 'fecha_fin'], name='colegios_as_colegio_d3b9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='bloque',
            index=models.Index(fields=['colegio', 'grado'], name='colegios_bl_colegio_312a66_idx'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['libro_especial'], name='colegios_cl_libro_e_69397c_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['usuario', 'fecha'], name='colegios_hi_usuario_b70c06_idx'),
        ),
    ]
