# Generated by Django 5.2.11 on 2026-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0011_asignacion_colegios_as_colegio_d3b9b1_idx_and_more'),
        ('configuracion', '0022_alter_materia_color'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['bloque', 'fecha'], name='colegios_cl_bloque__f62449_idx'),
        ),
    ]
