# Generated by Django 5.2.11 on 2026-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0012_clase_colegios_cl_bloque__f62449_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asignacion',
            new_name='prog_asigna_colegio_45aa3e_idx',
            old_name='colegios_as_colegio_d3b9b1_idx',
        ),
        migrations.RenameIndex(
            model_name='bloque',
            new_name='prog_bloque_colegio_1088b4_idx',
            old_name='colegios_bl_colegio_312a66_idx',
        ),
        migrations.RenameIndex(
            model_name='clase',
            new_name='prog_clases_colegio_967755_idx',
            old_name='colegios_cl_colegio_68f439_idx',
        ),
        migrations.RenameIndex(
            model_name='clase',
            new_name='prog_clases_fecha_9ddbe0_idx',
            old_name='colegios_cl_fecha_2a4f59_idx',
        ),
        migrations.RenameIndex(
            model_name='clase',
            new_name='prog_clases_profeso_a1af11_idx',
            old_name='colegios_cl_profeso_454e15_idx',
        ),
        migrations.RenameIndex(
            model_name='clase',
            new_name='prog_clases_libro_e_08ec5d_idx',
            old_name='colegios_cl_libro_e_69397c_idx',
        ),
        migrations.RenameIndex(
            model_name='clase',
            new_name='prog_clases_bloque__8c0d3a_idx',
            old_name='colegios_cl_bloque__f62449_idx',
        ),
        migrations.RenameIndex(
            model_name='historialcambio',
            new_name='prog_histor_objeto__e662d9_idx',
            old_name='colegios_hi_objeto__75aa6a_idx',
        ),
        migrations.RenameIndex(
            model_name='historialcambio',
            new_name='prog_histor_colegio_5aea2e_idx',
            old_name='colegios_hi_colegio_02309a_idx',
        ),
        migrations.RenameIndex(
            model_name='historialcambio',
            new_name='prog_histor_usuario_20ff41_idx',
            old_name='colegios_hi_usuario_b70c06_idx',
        ),
        migrations.AlterModelTable(
            name='asignacion',
            table='prog_asignaciones',
        ),
        migrations.AlterModelTable(
            name='bloque',
            table='prog_bloques',
        ),
        migrations.AlterModelTable(
            name='clase',
            table='prog_clases',
        ),
        migrations.AlterModelTable(
            name='claseparticular',
            table='prog_clases_particulares',
        ),
        migrations.AlterModelTable(
            name='grado',
            table='prog_grados',
        ),
        migrations.AlterModelTable(
            name='historialcambio',
            table='prog_historial_cambios',
        ),
    ]
