# Generated by Django 5.2.11 on 2026-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0016_remove_clasepersonalizada_material'),
        ('configuracion', '0025_documentoprofesor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clasepersonalizada',
            index=models.Index(fields=['fecha'], name='prog_clases_fecha_6049d6_idx'),
        ),
        migrations.AddIndex(
            model_name='clasepersonalizada',
            index=models.Index(fields=['profesor', 'fecha'], name='prog_clases_profeso_cccc01_idx'),
        ),
    ]
