# Generated by Django 5.2.11 on 2026-06-10 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0017_clasepersonalizada_prog_clases_fecha_6049d6_idx_and_more'),
        ('configuracion', '0025_documentoprofesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COLEGIO', 'Colegio'), ('PROFESOR', 'Profesor')], max_length=10)),
                ('profesor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('colegio_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_clase', models.DateField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones', to='colegios.clase')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones', to='configuracion.colegio')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones', to='configuracion.profesor')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cancelación de Clase',
                'verbose_name_plural': 'Cancelaciones de Clases',
                'db_table': 'prog_clases_cancelaciones',
                'ordering': ['-fecha_clase', '-registrado_en'],
                'indexes': [models.Index(fields=['tipo', 'fecha_clase'], name='prog_clases_tipo_ff3515_idx')],
            },
        ),
    ]
