# Generated by Django 5.2.11 on 2026-02-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Colegio')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('mapa_link', models.URLField(blank=True, null=True, verbose_name='Link de Maps')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Libro')),
                ('materia', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad / Número')),
                ('nombre_unidad', models.CharField(max_length=200, verbose_name='Nombre de la Unidad')),
                ('link_unidad', models.URLField(max_length=500, verbose_name='Link de la Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula / Documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
        ),
    ]
