# Generated by Django 5.2.11 on 2026-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido(s)'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='area_materia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Área / Materia que dicta'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='disponibilidad',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Mañana y Tarde', 'Mañana y Tarde'), ('Mañana y Noche', 'Mañana y Noche'), ('Tarde y Noche', 'Tarde y Noche'), ('Todo el día', 'Todo el día')], max_length=50, null=True, verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Unión libre', 'Unión libre'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fondo_pension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fondo de Pensión'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='talla_camisa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Talla Camisa'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], max_length=20, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre(s)'),
        ),
    ]
