# Generated by Django 5.2.11 on 2026-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_profesor_apellido_profesor_area_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='banco',
            field=models.CharField(blank=True, choices=[('Nequi', 'Nequi'), ('Bancolombia', 'Bancolombia'), ('Banco de Bogotá', 'Banco de Bogotá'), ('Davivienda', 'Davivienda'), ('Daviplata', 'Daviplata'), ('Nu', 'Nu')], max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='disponibilidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Disponibilidad'),
        ),
    ]
