# Generated by Django 5.2.11 on 2026-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_profesor_banco_alter_profesor_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='banco',
            field=models.CharField(blank=True, choices=[('Nequi', 'Nequi'), ('Bancolombia', 'Bancolombia'), ('Banco de Bogotá', 'Banco de Bogotá'), ('Davivienda', 'Davivienda'), ('Daviplata', 'Daviplata'), ('Nu', 'Nu'), ('BBVA', 'BBVA')], max_length=100, null=True, verbose_name='Banco'),
        ),
    ]
