# Generated by Django 5.2.11 on 2026-03-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_alter_profesor_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='disponibilidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Disponibilidad'),
        ),
    ]
