# Generated by Django 5.2.11 on 2026-03-19 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_alter_profesor_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NombreLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Libro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Unidad')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='configuracion.nombrelibro', verbose_name='Libro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='configuracion.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['libro__nombre', 'materia__nombre', 'numero'],
                'unique_together': {('libro', 'materia', 'numero')},
            },
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
