# Generated by Django 5.2.11 on 2026-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_materia_nombrelibro_unidad_delete_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colegio',
            options={'ordering': ['nombre', '-año'], 'verbose_name': 'Colegio', 'verbose_name_plural': 'Colegios'},
        ),
        migrations.AddField(
            model_name='colegio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='año',
            field=models.IntegerField(default=2026, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='departamento',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colegio',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Colegio'),
        ),
        migrations.AlterUniqueTogether(
            name='colegio',
            unique_together={('nombre', 'año')},
        ),
    ]
