# Generated by Django 5.2.11 on 2026-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_alter_colegio_options_colegio_activo_colegio_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
