# Generated by Django 5.2.11 on 2026-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_profesor_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='area_materia',
        ),
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='configuracion.materia', verbose_name='Materias que dicta'),
        ),
    ]
