# Generated by Django 5.2.11 on 2026-04-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_profesor_materias_m2m_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Color hexadecimal, ej: #e74c3c', max_length=7, verbose_name='Color'),
        ),
    ]
