# Generated by Django 5.2.11 on 2026-04-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_materia_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='eps',
            field=models.CharField(blank=True, choices=[('Nueva EPS', 'Nueva EPS'), ('Sura', 'Sura'), ('Sanitas', 'Sanitas'), ('Salud Total', 'Salud Total'), ('Compensar', 'Compensar'), ('Coosalud', 'Coosalud'), ('Famisanar', 'Famisanar'), ('Mutual Ser', 'Mutual Ser'), ('Aliansalud', 'Aliansalud'), ('Comfenalco', 'Comfenalco'), ('Coomeva', 'Coomeva'), ('Otra', 'Otra')], max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fondo_pension',
            field=models.CharField(blank=True, choices=[('Porvenir', 'Porvenir'), ('Protección', 'Protección'), ('Colfondos', 'Colfondos'), ('Old Mutual', 'Old Mutual'), ('Colpensiones', 'Colpensiones'), ('Otro', 'Otro')], max_length=100, null=True, verbose_name='Fondo de Pensión'),
        ),
    ]
