# Generated by Django 5.2.11 on 2026-04-04 16:18

import configuracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_alter_profesor_eps_alter_profesor_fondo_pension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='año',
            field=models.IntegerField(default=configuracion.models._anio_actual, verbose_name='Año'),
        ),
    ]
