# Generated by Django 5.2.11 on 2026-04-05 01:49

import programacion.configuracion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_fix_año_default_callable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColegioAño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(default=programacion.configuracion.models._anio_actual, verbose_name='Año')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='años', to='configuracion.colegio', verbose_name='Colegio')),
            ],
            options={
                'verbose_name': 'Colegio-Año',
                'verbose_name_plural': 'Colegios-Año',
                'ordering': ['colegio__nombre', '-año'],
                'unique_together': {('colegio', 'año')},
            },
        ),
    ]
