# Generated by Django 5.2.11 on 2026-04-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0014_populate_colegioano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colegio',
            options={'ordering': ['nombre'], 'verbose_name': 'Colegio', 'verbose_name_plural': 'Colegios'},
        ),
        migrations.AlterUniqueTogether(
            name='colegio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre del Colegio'),
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='año',
        ),
    ]
