# Generated by Django 5.2.11 on 2026-04-05 18:52

import programacion.configuracion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0015_alter_colegio_options_alter_colegio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colegioaño',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='colegioaño',
            name='colegio',
        ),
        migrations.CreateModel(
            name='ColegioAnio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=programacion.configuracion.models._anio_actual, verbose_name='Año')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anios', to='configuracion.colegio', verbose_name='Colegio')),
            ],
            options={
                'verbose_name': 'Colegio-Año',
                'verbose_name_plural': 'Colegios-Año',
                'ordering': ['colegio__nombre', '-anio'],
            },
        ),
    ]
