# Generated by Django 5.2.11 on 2026-04-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_alertaauditoria_colegio_and_more'),
        ('colegios', '0007_alter_asignacion_colegio_alter_bloque_colegio_and_more'),
        ('configuracion', '0016_alter_colegioaño_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColegioAño',
        ),
        migrations.AlterUniqueTogether(
            name='colegioanio',
            unique_together={('colegio', 'anio')},
        ),
    ]
