# Generated by Django 5.2.11 on 2026-04-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_delete_colegioaño_alter_colegioanio_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombrelibro',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace del Libro'),
        ),
    ]
