# Generated by Django 5.2.11 on 2026-04-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_nombrelibro_es_material_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nombrelibro',
            name='enlace',
        ),
    ]
