# Generated by Django 5.2.11 on 2026-04-14 15:37

import programacion.configuracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0021_colegioano_valor_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Color hexadecimal, ej: #e74c3c', max_length=7, validators=[programacion.configuracion.models._validate_hex_color], verbose_name='Color'),
        ),
    ]
