# Generated by Django 5.2.11 on 2026-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0022_alter_materia_color'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colegio',
            table='prog_colegios',
        ),
        migrations.AlterModelTable(
            name='colegioanio',
            table='prog_colegio_anios',
        ),
        migrations.AlterModelTable(
            name='materia',
            table='prog_materias',
        ),
        migrations.AlterModelTable(
            name='nombrelibro',
            table='prog_libros',
        ),
        migrations.AlterModelTable(
            name='profesor',
            table='prog_profesores',
        ),
        migrations.AlterModelTable(
            name='unidad',
            table='prog_unidades',
        ),
    ]
