# Generated by Django 5.2.11 on 2026-06-03 19:55

from datetime import date

from django.db import migrations, models


def _backfill_rango_periodos(apps, schema_editor):
    """Rellena fecha_inicio/fecha_fin de los ColegioAnio existentes.

    Todos los colegios arrancan en Calendario A, así que la ventana es el año
    natural (1-ene a 31-dic del anio). Replica periodo_por_defecto('A', anio) sin
    importarlo: las migraciones deben ser autosuficientes ante cambios futuros del modelo.
    """
    ColegioAnio = apps.get_model('configuracion', 'ColegioAnio')
    for ca in ColegioAnio.objects.filter(models.Q(fecha_inicio__isnull=True) | models.Q(fecha_fin__isnull=True)):
        if not ca.fecha_inicio:
            ca.fecha_inicio = date(ca.anio, 1, 1)
        if not ca.fecha_fin:
            ca.fecha_fin = date(ca.anio, 12, 31)
        ca.save(update_fields=['fecha_inicio', 'fecha_fin'])


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0023_alter_colegio_table_alter_colegioanio_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='calendario',
            field=models.CharField(choices=[('A', 'Calendario A (año natural: ene–dic)'), ('B', 'Calendario B (ago–jun del año siguiente)')], default='A', max_length=1, verbose_name='Calendario'),
        ),
        migrations.AddField(
            model_name='colegioanio',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin del periodo'),
        ),
        migrations.AddField(
            model_name='colegioanio',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio del periodo'),
        ),
        migrations.RunPython(_backfill_rango_periodos, migrations.RunPython.noop),
    ]
