# Generated by Django 5.2.11 on 2026-06-05 16:39

import django.db.models.deletion
import programacion.configuracion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0024_colegio_calendario_colegioanio_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=programacion.configuracion.models._documento_profesor_upload_to)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='configuracion.profesor')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de profesor',
                'verbose_name_plural': 'Documentos de profesor',
                'db_table': 'prog_profesores_documentos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
