# Generated by Django 5.2.11 on 2026-07-06 15:04

import django.db.models.deletion
import logistica.personalizacion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('SIMULACRO', 'Simulacro'), ('PENSAR', 'Pensar')], max_length=10)),
                ('archivo', models.FileField(upload_to=logistica.personalizacion.models._plantilla_upload_to)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_personalizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de personalización',
                'verbose_name_plural': 'Plantillas de personalización',
                'db_table': 'log_plantillas_personalizacion',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
