# Generated by Django 5.2.11 on 2026-07-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_personalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillapersonalizacion',
            name='tipo',
            field=models.CharField(choices=[('SIMULACRO', 'Simulacro'), ('PENSAR', 'Pensar'), ('MP', 'MP')], max_length=10),
        ),
    ]
