# Generated by Django 5.2.11 on 2026-03-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0002_claseparticular'),
        ('configuracion', '0003_alter_profesor_banco_alter_profesor_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio_nombre', models.CharField(max_length=200)),
                ('grado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('materia', models.CharField(max_length=100)),
                ('tematica', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('actividades', models.TextField(blank=True, default='')),
                ('fortalezas', models.TextField(blank=True, default='')),
                ('debilidades', models.TextField(blank=True, default='')),
                ('recomendaciones', models.TextField(blank=True, default='')),
                ('bibliografia', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='colegios.clase')),
                ('clase_particular', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='colegios.claseparticular')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='configuracion.profesor')),
            ],
            options={
                'verbose_name': 'Informe de Sesión',
                'verbose_name_plural': 'Informes de Sesión',
                'ordering': ['-fecha', 'colegio_nombre'],
            },
        ),
    ]
