# Generated by Django 5.2.11 on 2026-04-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0005_normalizacion_bd'),
        ('configuracion', '0011_alter_profesor_eps_alter_profesor_fondo_pension'),
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='informe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clase__isnull', False), ('clase_particular__isnull', True)), models.Q(('clase__isnull', True), ('clase_particular__isnull', False)), _connector='OR'), name='informe_exactamente_una_clase'),
        ),
    ]
