# Generated by Django 5.2.11 on 2026-06-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_informe_informe_exactamente_una_clase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='informe',
            table='prog_informes',
        ),
    ]
