# Generated by Django 5.2.11 on 2026-06-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0016_remove_clasepersonalizada_material'),
        ('informes', '0004_rename_clase_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='clase_personalizada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='colegios.clasepersonalizada'),
        ),
    ]
